# Note that you might have to increase the memory footprint of the docker-machine in order to run these containers
# docker-machine stop
# VBoxManage modifyvm default --cpus 2
# VBoxManage modifyvm default --memory 4096
# docker-machine start
version: '2'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes: 
      - ./migrations/1.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - POSTGRES_PASSWORD=password
